"""auto update

Revision ID: 3a18fc17f0bd
Revises: d27dcc6052eb
Create Date: 2026-03-31 01:13:53.260479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a18fc17f0bd'
down_revision: Union[str, Sequence[str], None] = 'd27dcc6052eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('file_key', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('is_file_post', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('investigation_flag', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('frozen_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'frozen_until')
    op.drop_column('user_profiles', 'investigation_flag')
    op.drop_column('posts', 'is_file_post')
    op.drop_column('posts', 'file_type')
    op.drop_column('posts', 'file_name')
    op.drop_column('posts', 'file_key')
    # ### end Alembic commands ###